version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Descriptions matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
      - do: dependent
        changed:
          file: 'package.json'
          required: ['package-lock.json', 'yarn.lock']
